name: CI

on:
  push:
    branches: [ main, FE_Dev ]
  pull_request:
    branches: [ main, FE_Dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm run install:all

    - name: Run client tests
      working-directory: ./client
      run: npm test -- --watchAll=false
      continue-on-error: true

    - name: Run server tests
      working-directory: ./Server
      run: npm test
      continue-on-error: true

    - name: Build client
      working-directory: ./client
      run: npm run build