name: CI

on:
  push:
    branches: [ main, FE_Dev ]
  pull_request:
    branches: [ main, FE_Dev ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm run install:all
          cd client && npm install --save-dev eslint-plugin-prettier
          cd ../Server && npm install --save-dev eslint-plugin-prettier

      - name: Run ESLint
        run: |
          cd client && npm run lint
          cd ../Server && npm run lint

      - name: Run Prettier check
        run: |
          cd client && npm run format:check
          cd ../Server && npm run format:check

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm run install:all

    - name: Run client tests
      working-directory: ./client
      run: npm test -- --watchAll=false
      continue-on-error: true

    - name: Run server tests
      working-directory: ./Server
      run: npm test
      continue-on-error: true

    - name: Build client
      working-directory: ./client
      run: npm run build