name: Build and Publish Docker Image

on:
  push:
    branches: [ main, FE_Dev ]
  pull_request:
    branches: [ main, FE_Dev ]

env:
  REPO_OWNER: ${{ github.repository_owner }}
  LOWER_REPO_OWNER: ${{ format('{0}', github.repository_owner) }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Convert to lowercase
        run: |
          echo "LOWER_REPO_OWNER=$(echo ${{ env.REPO_OWNER }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_REPO_OWNER }}/cs5500-project:latest
            ghcr.io/${{ env.LOWER_REPO_OWNER }}/cs5500-project:${{ github.sha }}